# Generated by Django 3.0.8 on 2020-07-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200724_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectLink',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
